version: '0.1'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: SimpleIPTVserver
    restart: always
    working_dir: /IPTV/
    volumes:
      - ../src:/IPTV
  nginx:
    image: nginx:latest
    container_name: SimpleIPTVweb
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src:/IPTV
      - ./nginx:/etc/nginx/conf.d
